version: "3.8"
services:
  react:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: mystocks-react
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./:/usr/src/app/mystocks-react
      - /usr/src/app/mystocks-react/node_modules
